/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-13 18:58:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1778689624000L));
    _jspx_dependants.put("jar:file:/C:/Users/KARTHIK%20AT/Downloads/JSP-Ecom-Application-main/JSP-Ecom-Application-main/.tomcat/apache-tomcat-9.0.87/webapps/jsp-servlet-ecommerce-website/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/head.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"site-wrap\">\n");
      out.write("    ");
 request.setAttribute("about_active", "active"); 
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"bg-light py-3\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-12 mb-0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a> <span class=\"mx-2 mb-0\">/</span> <strong\n");
      out.write("                        class=\"text-black\">About</strong></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"site-section border-bottom\" data-aos=\"fade\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row mb-5\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <div class=\"block-16\">\n");
      out.write("                        <figure>\n");
      out.write("                            <img src=\"static/images/blog_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid rounded\">\n");
      out.write("                            <a href=\"https://vimeo.com/channels/staffpicks/93951774\" class=\"play-button popup-vimeo\">\n");
      out.write("                                <span class=\"ion-md-play\"></span>\n");
      out.write("                            </a>\n");
      out.write("                        </figure>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-1\">\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-5\">\n");
      out.write("                    <div class=\"site-section-heading pt-3 mb-4\">\n");
      out.write("                        <h2 class=\"text-black\">How JSP Ecom Started</h2>\n");
      out.write("                    </div>\n");
      out.write("                        <p>\n");
      out.write("                            JSP Ecom was built as a practical JSP/Servlet storefront for learning how a real e-commerce\n");
      out.write("                            flow works end to end. The project covers browsing, product detail pages, carts, checkout,\n");
      out.write("                            and order history in one connected application.\n");
      out.write("                        </p>\n");
      out.write("                        <p>\n");
      out.write("                            The goal of this redesign is to make the storefront feel editorial and modern while keeping\n");
      out.write("                            the Java backend, JDBC data flow, and Tomcat deployment model simple and readable.\n");
      out.write("                        </p>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"site-section border-bottom\" data-aos=\"fade\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center mb-5\">\n");
      out.write("                <div class=\"col-md-7 site-section-heading text-center pt-4\">\n");
      out.write("                    <h2>The Team</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 col-lg-3\">\n");
      out.write("\n");
      out.write("                    <div class=\"block-38 text-center\">\n");
      out.write("                        <div class=\"block-38-img\">\n");
      out.write("                            <div class=\"block-38-header\">\n");
      out.write("                                <img src=\"static/images/person_1.jpg\" alt=\"Image placeholder\" class=\"mb-4\">\n");
      out.write("                                <h3 class=\"block-38-heading h4\">Frontend Experience</h3>\n");
      out.write("                                <p class=\"block-38-subheading\">Visual identity</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"block-38-body\">\n");
      out.write("                                <p>Handles the visual language, hero sections, product cards, and responsive layout used\n");
      out.write("                                    across the storefront.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 col-lg-3\">\n");
      out.write("                    <div class=\"block-38 text-center\">\n");
      out.write("                        <div class=\"block-38-img\">\n");
      out.write("                            <div class=\"block-38-header\">\n");
      out.write("                                <img src=\"static/images/person_2.jpg\" alt=\"Image placeholder\" class=\"mb-4\">\n");
      out.write("                                <h3 class=\"block-38-heading h4\">Catalog Layer</h3>\n");
      out.write("                                <p class=\"block-38-subheading\">Products and categories</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"block-38-body\">\n");
      out.write("                                <p>Keeps product browsing, search, and category collections aligned with the database-backed\n");
      out.write("                                    listing pages.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 col-lg-3\">\n");
      out.write("                    <div class=\"block-38 text-center\">\n");
      out.write("                        <div class=\"block-38-img\">\n");
      out.write("                            <div class=\"block-38-header\">\n");
      out.write("                                <img src=\"static/images/person_3.jpg\" alt=\"Image placeholder\" class=\"mb-4\">\n");
      out.write("                                <h3 class=\"block-38-heading h4\">Cart Logic</h3>\n");
      out.write("                                <p class=\"block-38-subheading\">Session management</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"block-38-body\">\n");
      out.write("                                <p>Manages product quantity, cart totals, checkout flow, and the final order confirmation path.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 col-lg-3\">\n");
      out.write("                    <div class=\"block-38 text-center\">\n");
      out.write("                        <div class=\"block-38-img\">\n");
      out.write("                            <div class=\"block-38-header\">\n");
      out.write("                                <img src=\"static/images/person_4.jpg\" alt=\"Image placeholder\" class=\"mb-4\">\n");
      out.write("                                <h3 class=\"block-38-heading h4\">Deployment Flow</h3>\n");
      out.write("                                <p class=\"block-38-subheading\">Tomcat and WAR packaging</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"block-38-body\">\n");
      out.write("                                <p>Packages the application into a WAR, clears stale deployments, and starts Tomcat with the latest UI.\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"site-section site-section-sm site-blocks-1 border-0\" data-aos=\"fade\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4\" data-aos=\"fade-up\" data-aos-delay=\"\">\n");
      out.write("                    <div class=\"icon mr-4 align-self-start\">\n");
      out.write("                        <span class=\"icon-truck\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text\">\n");
      out.write("                        <h2 class=\"text-uppercase\">Fast delivery</h2>\n");
      out.write("                        <p>Delivery messaging is kept clear and premium so the storefront feels trustworthy from the first screen.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("                    <div class=\"icon mr-4 align-self-start\">\n");
      out.write("                        <span class=\"icon-refresh2\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text\">\n");
      out.write("                        <h2 class=\"text-uppercase\">Easy returns</h2>\n");
      out.write("                        <p>Shopping flows are arranged to reduce friction and make browsing, cart review, and checkout simple.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4\" data-aos=\"fade-up\" data-aos-delay=\"200\">\n");
      out.write("                    <div class=\"icon mr-4 align-self-start\">\n");
      out.write("                        <span class=\"icon-help\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text\">\n");
      out.write("                        <h2 class=\"text-uppercase\">Human support</h2>\n");
      out.write("                        <p>Support messaging stays clear and direct, matching the cleaner visual system used across the app.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/footer.jsp", out, false);
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/scripts.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
