/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-13 18:07:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1778689624000L));
    _jspx_dependants.put("jar:file:/C:/Users/KARTHIK%20AT/Downloads/JSP-Ecom-Application-main/JSP-Ecom-Application-main/.tomcat/apache-tomcat-9.0.87/webapps/jsp-servlet-ecommerce-website/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); 
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/head.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"site-wrap\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"hero-split hero-split--merch\" data-aos=\"fade\">\n");
      out.write("        <div class=\"hero-grid\">\n");
      out.write("            <div class=\"hero-copy\">\n");
      out.write("                <div class=\"hero-kicker\">Fan drops / limited offers</div>\n");
      out.write("                <h1 class=\"hero-title\">Royal Challengers Bangalore merch, curated like a premium launch.</h1>\n");
      out.write("                <p>\n");
      out.write("                    A merch-first storefront for RCB fans. Shop jerseys, caps,\n");
      out.write("                    hoodies, and match-day essentials with a polished, premium home experience.\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <div class=\"hero-offer-strip\">\n");
      out.write("                    <span class=\"offer-chip offer-chip--accent\">RCB matchday capsule</span>\n");
      out.write("                    <span class=\"offer-chip\">Limited offers</span>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"hero-actions\">\n");
      out.write("                    <a href=\"#merch-capsules\" class=\"btn btn-primary\">Explore merch</a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop\" class=\"btn btn-outline-primary\">Open shop</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"hero-stat-grid\">\n");
      out.write("                    <div class=\"stat-card\">\n");
      out.write("                        <strong>02</strong>\n");
      out.write("                        <span>Fan capsules</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stat-card\">\n");
      out.write("                        <strong>24h</strong>\n");
      out.write("                        <span>Drop-ready ordering</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stat-card\">\n");
      out.write("                        <strong>Pro</strong>\n");
      out.write("                        <span>SaaS-style layout</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"hero-panel\">\n");
      out.write("                <div class=\"hero-stack hero-stack--single\">\n");
      out.write("                    <div class=\"hero-card hero-card--primary\">\n");
      out.write("                        <div class=\"hero-badge\">RCB spotlight</div>\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/puma-rcb-jersey.png?v=20260506\"\n");
      out.write("                             alt=\"Royal Challengers merchandise spotlight\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <div class=\"site-section site-section-sm site-blocks-1\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4\" data-aos=\"fade-up\" data-aos-delay=\"\">\n");
      out.write("                    <div class=\"icon mr-4 align-self-start\">\n");
      out.write("                        <span class=\"icon-truck\"></span>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"text\">\n");
      out.write("                        <h2 class=\"text-uppercase\">Fast delivery</h2>\n");
      out.write("                        <p>Streamlined delivery experience with a storefront that feels premium from the first click.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("                    <div class=\"icon mr-4 align-self-start\">\n");
      out.write("                        <span class=\"icon-refresh2\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text\">\n");
      out.write("                        <h2 class=\"text-uppercase\">Easy returns</h2>\n");
      out.write("                        <p>A clear product experience that makes shopping simple, confident, and visually focused.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4\" data-aos=\"fade-up\" data-aos-delay=\"200\">\n");
      out.write("                    <div class=\"icon mr-4 align-self-start\">\n");
      out.write("                        <span class=\"icon-help\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text\">\n");
      out.write("                        <h2 class=\"text-uppercase\">Support that feels human</h2>\n");
      out.write("                        <p>Helpful, high-trust messaging that matches the new editorial storefront experience.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/collections-section.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/featured-products.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"site-section merch-section\" id=\"merch-capsules\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center mb-5\">\n");
      out.write("                <div class=\"col-md-9 site-section-heading text-center pt-4\">\n");
      out.write("                    <div class=\"section-kicker section-kicker--dark\">Merch capsules</div>\n");
      out.write("                    <h2>Royal Challengers Bangalore</h2>\n");
      out.write("                    <p class=\"section-subtitle mx-auto\">\n");
      out.write("                        Curated fan gear with a premium launch feel, built for match day only.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"merch-grid merch-grid--single\">\n");
      out.write("                <article class=\"merch-card merch-card--rcb\" data-aos=\"fade-up\">\n");
      out.write("                    <div class=\"merch-card__media\">\n");
      out.write("                        <span class=\"merch-card__tag\">IPL fan kit</span>\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/puma-rcb-jersey.png?v=20260506\"\n");
      out.write("                             alt=\"Royal Challengers fan merch\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"merch-card__body\">\n");
      out.write("                        <div class=\"merch-card__eyebrow\">Royal Challengers Bangalore</div>\n");
      out.write("                        <h3>RCB match-day merch</h3>\n");
      out.write("                        <p>\n");
      out.write("                            Jerseys, caps, and supporter essentials wrapped in a vivid red-and-gold story.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"merch-card__meta\">Offer ends in: <strong>02:14:08</strong></div>\n");
      out.write("                        <div class=\"merch-card__actions\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop\" class=\"btn btn-primary btn-sm\">Shop RCB merch</a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop\" class=\"btn btn-outline-primary btn-sm\">See more drops</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </article>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/footer.jsp", out, false);
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/scripts.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
