/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-13 18:38:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1778689624000L));
    _jspx_dependants.put("jar:file:/C:/Users/KARTHIK%20AT/Downloads/JSP-Ecom-Application-main/JSP-Ecom-Application-main/.tomcat/apache-tomcat-9.0.87/webapps/jsp-servlet-ecommerce-website/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/head.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"auth-screen\">\n");
      out.write("    <div class=\"auth-visual\">\n");
      out.write("        <div class=\"auth-visual-card\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/puma-rcb-jersey.png?v=20260506\" alt=\"Puma RCB Jersey\">\n");
      out.write("            <div class=\"auth-visual-copy\">\n");
      out.write("                <div class=\"auth-kicker\">Member access</div>\n");
      out.write("                <h1 class=\"auth-title\" style=\"color:#fff !important;\">Welcome back.</h1>\n");
      out.write("                <p class=\"auth-note\" style=\"color:rgba(255,255,255,0.78); max-width: 460px;\">\n");
      out.write("                    Sign in to continue where you left off, manage your cart, and keep the storefront experience seamless.\n");
      out.write("                </p>\n");
      out.write("                <div class=\"chip-row\">\n");
      out.write("                    <span class=\"chip\">Fast checkout</span>\n");
      out.write("                    <span class=\"chip\">Saved orders</span>\n");
      out.write("                    <span class=\"chip\">Profile sync</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"auth-shell\">\n");
      out.write("        <div class=\"auth-panel\">\n");
      out.write("            <div class=\"auth-brand\">JSP Ecom</div>\n");
      out.write("            <div class=\"auth-card\">\n");
      out.write("                <div class=\"auth-kicker\" style=\"color: var(--olive);\">Login</div>\n");
      out.write("                <h2 class=\"auth-title\">Access your account</h2>\n");
      out.write("                <p class=\"auth-note\">Use your username and password to return to your storefront, orders, and profile.</p>\n");
      out.write("\n");
      out.write("                <form action=\"login?status=typed\" method=\"post\" class=\"auth-form\">\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                        <input class=\"form-control input100\" type=\"text\" name=\"username\" placeholder=\"Username\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                        <input class=\"form-control input100\" type=\"password\" name=\"password\" placeholder=\"Password\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center mb-4 flex-wrap\" style=\"gap: 12px;\">\n");
      out.write("                        <label class=\"d-flex align-items-center mb-0\" style=\"gap: 8px;\">\n");
      out.write("                            <input type=\"checkbox\" name=\"remember-me-checkbox\">\n");
      out.write("                            <span class=\"small text-muted\">Remember me</span>\n");
      out.write("                        </label>\n");
      out.write("                        <a href=\"#\" class=\"auth-link\">Forgot password?</a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button type=\"submit\" class=\"login100-form-btn btn btn-primary w-100\">Login</button>\n");
      out.write("                </form>\n");
      out.write("                <div class=\"text-center mt-4\">\n");
      out.write("                    <p class=\"mb-0 text-muted\">\n");
      out.write("                        Don't have an account?\n");
      out.write("                        <a href=\"register.jsp\" class=\"auth-link\">Create one</a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/scripts.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>Login</title>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"static/images/logo.png\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/vendor/bootstrap/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/vendor/animate/animate.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/vendor/css-hamburgers/hamburgers.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/vendor/animsition/css/animsition.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/vendor/select2/select2.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/vendor/daterangepicker/daterangepicker.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/util.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/main.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/magnific-popup.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/jquery-ui.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/owl.theme.default.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/aos.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/style.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"limiter\">\n");
      out.write("    <div class=\"container-login100\">\n");
      out.write("        <div class=\"shadow-lg p-2 p-lg-5 rounded\" data-aos=\"fade-up\">\n");
      out.write("            <div class=\"wrap-login100 p-t-50 p-b-90\">\n");
      out.write("                <form action=\"login?status=typed\" method=\"post\" class=\"login100-form validate-form flex-sb flex-w\">\n");
      out.write("                    <span class=\"login100-form-title p-b-51\">\n");
      out.write("                        Login\n");
      out.write("                    </span>\n");
      out.write("\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"wrap-input100 validate-input m-b-16\" data-validate=\"Username is required\">\n");
      out.write("                        <input class=\"input100\" type=\"text\" name=\"username\" placeholder=\"Username\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"wrap-input100 validate-input m-b-16\" data-validate=\"Password is required\">\n");
      out.write("                        <input class=\"input100\" type=\"password\" name=\"password\" placeholder=\"Password\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"flex-sb-m w-full p-t-3 p-b-24\">\n");
      out.write("                        <div class=\"contact100-form-checkbox\">\n");
      out.write("                            <input class=\"input-checkbox100\" id=\"ckb1\" type=\"checkbox\" name=\"remember-me-checkbox\">\n");
      out.write("                            <label class=\"label-checkbox100\" for=\"ckb1\">\n");
      out.write("                                Remember me\n");
      out.write("                            </label>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <a href=\"#\" class=\"txt1\">\n");
      out.write("                                Forgot?\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"container-login100-form-btn m-t-17\">\n");
      out.write("                        <button type=\"submit\" class=\"login100-form-btn\">\n");
      out.write("                            Login\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"text-center\">\n");
      out.write("                <p class=\"txt1\" style=\"color: #999999\">\n");
      out.write("                    Don't have an account?\n");
      out.write("                    <a href=\"register.jsp\" class=\"txt1\">\n");
      out.write("                        Create here\n");
      out.write("                    </a>\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"dropDownSelect1\"></div>\n");
      out.write("\n");
      out.write("<script src=\"static/vendor/jquery/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"static/vendor/animsition/js/animsition.min.js\"></script>\n");
      out.write("<script src=\"static/vendor/bootstrap/js/popper.js\"></script>\n");
      out.write("<script src=\"static/vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"static/vendor/select2/select2.min.js\"></script>\n");
      out.write("<script src=\"static/vendor/daterangepicker/moment.min.js\"></script>\n");
      out.write("<script src=\"static/vendor/daterangepicker/daterangepicker.js\"></script>\n");
      out.write("<script src=\"static/vendor/countdowntime/countdowntime.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"static/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"static/js/jquery-ui.js\"></script>\n");
      out.write("<script src=\"static/js/popper.min.js\"></script>\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"static/js/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"static/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("<script src=\"static/js/aos.js\"></script>\n");
      out.write("<script src=\"static/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
