/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-13 18:38:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1778689624000L));
    _jspx_dependants.put("jar:file:/C:/Users/KARTHIK%20AT/Downloads/JSP-Ecom-Application-main/JSP-Ecom-Application-main/.tomcat/apache-tomcat-9.0.87/webapps/jsp-servlet-ecommerce-website/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/head.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"auth-screen\">\n");
      out.write("    <div class=\"auth-visual\">\n");
      out.write("        <div class=\"auth-visual-card\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/red-bull-racing-capsule.svg?v=20260506\" alt=\"Red Bull Racing merch capsule\">\n");
      out.write("            <div class=\"auth-visual-copy\">\n");
      out.write("                <div class=\"auth-kicker\">Create account</div>\n");
      out.write("                <h1 class=\"auth-title\" style=\"color:#fff !important;\">Unlock merch drops.</h1>\n");
      out.write("                <p class=\"auth-note\" style=\"color:rgba(255,255,255,0.78); max-width: 460px;\">\n");
      out.write("                    Build your account to save Royal Challengers and Red Bull Racing fan gear, track orders,\n");
      out.write("                    and move through checkout faster.\n");
      out.write("                </p>\n");
      out.write("                <div class=\"chip-row\">\n");
      out.write("                    <span class=\"chip\">RCB drops</span>\n");
      out.write("                    <span class=\"chip\">Red Bull Racing</span>\n");
      out.write("                    <span class=\"chip\">Secure access</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"auth-shell\">\n");
      out.write("        <div class=\"auth-panel\">\n");
      out.write("            <div class=\"auth-brand\">JSP Ecom</div>\n");
      out.write("            <div class=\"auth-card\">\n");
      out.write("                <div class=\"auth-kicker\" style=\"color: var(--olive);\">Sign up</div>\n");
      out.write("                <h2 class=\"auth-title\">Create your merch account</h2>\n");
      out.write("                <p class=\"auth-note\">Register once to personalize the storefront, save fan drops, and keep your shopping history in one place.</p>\n");
      out.write("\n");
      out.write("                <form action=\"register\" method=\"post\" class=\"auth-form\" enctype=\"multipart/form-data\">\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"mb-4 text-center\">\n");
      out.write("                        <label class=\"m-0\" for=\"imgInp\" style=\"cursor: pointer; display: inline-block;\">\n");
      out.write("                            <img id=\"blah\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/blank_avatar.png?v=20260506\" alt=\"Profile preview\"\n");
      out.write("                                 style=\"width: 8.5rem; height: 8.5rem; object-fit: cover; border-radius: 50%;\">\n");
      out.write("                            <div class=\"mt-3 text-muted small\">Click to upload profile image</div>\n");
      out.write("                        </label>\n");
      out.write("                        <input name=\"profile-image\" type=\"file\" id=\"imgInp\" style=\"display: none;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                        <input class=\"form-control input100\" type=\"text\" name=\"username\" placeholder=\"Username\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                        <input class=\"form-control input100\" type=\"password\" name=\"password\" placeholder=\"Password\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                        <input class=\"form-control input100\" type=\"password\" name=\"repeat-password\" placeholder=\"Repeat password\">\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"login100-form-btn btn btn-primary w-100\">Sign up</button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <div class=\"text-center mt-4\">\n");
      out.write("                    <p class=\"mb-0 text-muted\">\n");
      out.write("                        Already have an account?\n");
      out.write("                        <a href=\"login.jsp\" class=\"auth-link\">Login here</a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/scripts.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
